version: "3.8"

services:
  postventa-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postventa
      - POSTGRES_USER=postventa
    volumes:
      - postventadata:/var/lib/postgresql/data
    ports: 
      - 5431:5432

  postventa-api:
    build: .
    environment:
      - type=postgres
      - host=postventa-db
      - port=5431
      - username=postventa
      - password=postventa
      - database=postventa
      - connectionName=postventa
      - PORT=3000
    depends_on:
      - postventa-db
    ports: 
      - 3000:3000

  postventa-web:
    build: ./../post_ventas_frontend/
    depends_on:
      - postventa-api
    ports: 
      - 4201:4201
      
volumes: 
  postventadata:
    driver: local
